version: "3.7"

services:
    # image project
    app:
        container_name: deploycode-laravel
        build:
            context: ./
            dockerfile: Dockerfile
            args: 
                user: deploycode
                uid: 1000
        image: deploycode/laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        container_name: deploycode-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 81:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        container_name: deploycode-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3388:3306
        networks: 
            - laravel

    # queue
    queue:
        build: 
            args: 
                user: deploycode
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: deploycode-queue
        image: deploycode/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www/core
        depends_on: 
            - redis
            - app
        networks: 
            - laravel

    # redis
    redis:
        container_name: deploycode-redis
        image: redis:latest
        networks: 
            - laravel

    #phpmyadmin
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        container_name: deploycode-phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 8081:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        networks:
            - laravel

networks: 
    laravel:
        driver: bridge
